version: '3'

services: 
    postgres-db:
        container_name: postgres-hst
        image: postgres
        restart: always
        environment: 
            - "POSTGRES_PASSWORD=Postgres2018!"
            - "POSTGRES_USER=leonardo"
            - "POSTGRES_DB=db_test"
        ports: 
            - "5432:5432"
        expose:
            - "5432"
        volumes: 
            - ./data:/var/lib/postgresql/data
        networks: 
            - local-network
    pgadmin-db:
        container_name: postgres-pgadmin
        image: dpage/pgadmin4
        restart: always
        environment: 
            - "PGADMIN_DEFAULT_EMAIL=leoframires@gmail.com"
            - "PGADMIN_DEFAULT_PASSWORD=1234"
        ports: 
            - "1234:80"
        expose:
            - "1234"
        volumes: 
            - ./pgadmin:/var/lib/pgadmin
        networks: 
            - local-network
        depends_on: 
            - postgres-db
    python-env:
        build:
            dockerfile: ./.
            context: ./python/.
        container_name: py-env
        volumes: 
            - .:/usr/src/
        networks: 
            - local-network
        depends_on: 
            - pgadmin-db
            - postgres-db
networks: 
    local-network:
        driver: bridge
